# Generated by Django 4.1 on 2022-08-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0002_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='text',
            field=models.CharField(max_length=600),
        ),
    ]
